name: Terraform Destroy
on:
    workflow_dispatch:

env:
  TF_VERSION: "1.13.3"
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

  TF_VAR_public_key: ${{ secrets.PUBLIC_KEY }}
  
  TF_VAR_region: ${{ secrets.AWS_REGION }}
  TF_VAR_vpc_cidr_block: ${{ secrets.VPC_CIDR_BLOCK }}

  TF_VAR_ssh_access_ip: ${{ secrets.SSH_ACCESS_IP }}
  TF_VAR_public_subnet_cidr_block: ${{ secrets.PUBLIC_SUBNET_CIDR_BLOCK }}
  TF_VAR_private_subnet_cidr_block: ${{ secrets.PRIVATE_SUBNET_CIDR_BLOCK }}

  TF_VAR_dbname: ${{ secrets.DBNAME }}
  TF_VAR_dbuser: ${{ secrets.DBUSER }}
  TF_VAR_dbpassword: ${{ secrets.DBPASSWORD }}

jobs:
    destroy:
        name: terraform destroy
        runs-on: ubuntu-latest
        environment: destroy-approval

        steps:
            - name: Get the Repo
              uses: actions/checkout@v4

            - name: Configure AWS Creds
              uses: aws-actions/configure-aws-credentials@v5.1.0
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Perform Terraform Init
              run: |
                terraform init -input=false
            
            - name: Terraform Destroy
              run: |
                terraform destroy -auto-approve


              
            
